repos:
- hooks:
  - id: check-yaml
  - id: trailing-whitespace
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
- hooks:
  - id: commitizen
  - id: commitizen-branch
    stages: [push]
  repo: https://github.com/commitizen-tools/commitizen
  rev: v2.37.0
